// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/sharm/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewJobQueueMock creates a new instance of JobQueueMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobQueueMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobQueueMock {
	mock := &JobQueueMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JobQueueMock is an autogenerated mock type for the JobQueue type
type JobQueueMock struct {
	mock.Mock
}

type JobQueueMock_Expecter struct {
	mock *mock.Mock
}

func (_m *JobQueueMock) EXPECT() *JobQueueMock_Expecter {
	return &JobQueueMock_Expecter{mock: &_m.Mock}
}

// Claim provides a mock function for the type JobQueueMock
func (_mock *JobQueueMock) Claim() (*domain.Job, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Claim")
	}

	var r0 *domain.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*domain.Job, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *domain.Job); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobQueueMock_Claim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claim'
type JobQueueMock_Claim_Call struct {
	*mock.Call
}

// Claim is a helper method to define mock.On call
func (_e *JobQueueMock_Expecter) Claim() *JobQueueMock_Claim_Call {
	return &JobQueueMock_Claim_Call{Call: _e.mock.On("Claim")}
}

func (_c *JobQueueMock_Claim_Call) Run(run func()) *JobQueueMock_Claim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JobQueueMock_Claim_Call) Return(job *domain.Job, err error) *JobQueueMock_Claim_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *JobQueueMock_Claim_Call) RunAndReturn(run func() (*domain.Job, error)) *JobQueueMock_Claim_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function for the type JobQueueMock
func (_mock *JobQueueMock) Complete(jobID int64) error {
	ret := _mock.Called(jobID)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(jobID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobQueueMock_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type JobQueueMock_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - jobID int64
func (_e *JobQueueMock_Expecter) Complete(jobID interface{}) *JobQueueMock_Complete_Call {
	return &JobQueueMock_Complete_Call{Call: _e.mock.On("Complete", jobID)}
}

func (_c *JobQueueMock_Complete_Call) Run(run func(jobID int64)) *JobQueueMock_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JobQueueMock_Complete_Call) Return(err error) *JobQueueMock_Complete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobQueueMock_Complete_Call) RunAndReturn(run func(jobID int64) error) *JobQueueMock_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Enqueue provides a mock function for the type JobQueueMock
func (_mock *JobQueueMock) Enqueue(mediaID string, jobType domain.JobType, codec domain.Codec, fps int) (*domain.Job, error) {
	ret := _mock.Called(mediaID, jobType, codec, fps)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 *domain.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, domain.JobType, domain.Codec, int) (*domain.Job, error)); ok {
		return returnFunc(mediaID, jobType, codec, fps)
	}
	if returnFunc, ok := ret.Get(0).(func(string, domain.JobType, domain.Codec, int) *domain.Job); ok {
		r0 = returnFunc(mediaID, jobType, codec, fps)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, domain.JobType, domain.Codec, int) error); ok {
		r1 = returnFunc(mediaID, jobType, codec, fps)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobQueueMock_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type JobQueueMock_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - mediaID string
//   - jobType domain.JobType
//   - codec domain.Codec
//   - fps int
func (_e *JobQueueMock_Expecter) Enqueue(mediaID interface{}, jobType interface{}, codec interface{}, fps interface{}) *JobQueueMock_Enqueue_Call {
	return &JobQueueMock_Enqueue_Call{Call: _e.mock.On("Enqueue", mediaID, jobType, codec, fps)}
}

func (_c *JobQueueMock_Enqueue_Call) Run(run func(mediaID string, jobType domain.JobType, codec domain.Codec, fps int)) *JobQueueMock_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 domain.JobType
		if args[1] != nil {
			arg1 = args[1].(domain.JobType)
		}
		var arg2 domain.Codec
		if args[2] != nil {
			arg2 = args[2].(domain.Codec)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *JobQueueMock_Enqueue_Call) Return(job *domain.Job, err error) *JobQueueMock_Enqueue_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *JobQueueMock_Enqueue_Call) RunAndReturn(run func(mediaID string, jobType domain.JobType, codec domain.Codec, fps int) (*domain.Job, error)) *JobQueueMock_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// Fail provides a mock function for the type JobQueueMock
func (_mock *JobQueueMock) Fail(jobID int64, errMsg string) error {
	ret := _mock.Called(jobID, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for Fail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, string) error); ok {
		r0 = returnFunc(jobID, errMsg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobQueueMock_Fail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fail'
type JobQueueMock_Fail_Call struct {
	*mock.Call
}

// Fail is a helper method to define mock.On call
//   - jobID int64
//   - errMsg string
func (_e *JobQueueMock_Expecter) Fail(jobID interface{}, errMsg interface{}) *JobQueueMock_Fail_Call {
	return &JobQueueMock_Fail_Call{Call: _e.mock.On("Fail", jobID, errMsg)}
}

func (_c *JobQueueMock_Fail_Call) Run(run func(jobID int64, errMsg string)) *JobQueueMock_Fail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobQueueMock_Fail_Call) Return(err error) *JobQueueMock_Fail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobQueueMock_Fail_Call) RunAndReturn(run func(jobID int64, errMsg string) error) *JobQueueMock_Fail_Call {
	_c.Call.Return(run)
	return _c
}

// ResetStalled provides a mock function for the type JobQueueMock
func (_mock *JobQueueMock) ResetStalled() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResetStalled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobQueueMock_ResetStalled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetStalled'
type JobQueueMock_ResetStalled_Call struct {
	*mock.Call
}

// ResetStalled is a helper method to define mock.On call
func (_e *JobQueueMock_Expecter) ResetStalled() *JobQueueMock_ResetStalled_Call {
	return &JobQueueMock_ResetStalled_Call{Call: _e.mock.On("ResetStalled")}
}

func (_c *JobQueueMock_ResetStalled_Call) Run(run func()) *JobQueueMock_ResetStalled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *JobQueueMock_ResetStalled_Call) Return(err error) *JobQueueMock_ResetStalled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobQueueMock_ResetStalled_Call) RunAndReturn(run func() error) *JobQueueMock_ResetStalled_Call {
	_c.Call.Return(run)
	return _c
}
