// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewFileSystemMock creates a new instance of FileSystemMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileSystemMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileSystemMock {
	mock := &FileSystemMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FileSystemMock is an autogenerated mock type for the FileSystem type
type FileSystemMock struct {
	mock.Mock
}

type FileSystemMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FileSystemMock) EXPECT() *FileSystemMock_Expecter {
	return &FileSystemMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type FileSystemMock
func (_mock *FileSystemMock) Create(path string) (*os.File, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*os.File, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FileSystemMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type FileSystemMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - path string
func (_e *FileSystemMock_Expecter) Create(path interface{}) *FileSystemMock_Create_Call {
	return &FileSystemMock_Create_Call{Call: _e.mock.On("Create", path)}
}

func (_c *FileSystemMock_Create_Call) Run(run func(path string)) *FileSystemMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FileSystemMock_Create_Call) Return(file *os.File, err error) *FileSystemMock_Create_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *FileSystemMock_Create_Call) RunAndReturn(run func(path string) (*os.File, error)) *FileSystemMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function for the type FileSystemMock
func (_mock *FileSystemMock) MkdirAll(path string, perm os.FileMode) error {
	ret := _mock.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(path, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FileSystemMock_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type FileSystemMock_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
//   - perm os.FileMode
func (_e *FileSystemMock_Expecter) MkdirAll(path interface{}, perm interface{}) *FileSystemMock_MkdirAll_Call {
	return &FileSystemMock_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *FileSystemMock_MkdirAll_Call) Run(run func(path string, perm os.FileMode)) *FileSystemMock_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 os.FileMode
		if args[1] != nil {
			arg1 = args[1].(os.FileMode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FileSystemMock_MkdirAll_Call) Return(err error) *FileSystemMock_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FileSystemMock_MkdirAll_Call) RunAndReturn(run func(path string, perm os.FileMode) error) *FileSystemMock_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type FileSystemMock
func (_mock *FileSystemMock) Open(path string) (*os.File, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 *os.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*os.File, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FileSystemMock_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type FileSystemMock_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - path string
func (_e *FileSystemMock_Expecter) Open(path interface{}) *FileSystemMock_Open_Call {
	return &FileSystemMock_Open_Call{Call: _e.mock.On("Open", path)}
}

func (_c *FileSystemMock_Open_Call) Run(run func(path string)) *FileSystemMock_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FileSystemMock_Open_Call) Return(file *os.File, err error) *FileSystemMock_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *FileSystemMock_Open_Call) RunAndReturn(run func(path string) (*os.File, error)) *FileSystemMock_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type FileSystemMock
func (_mock *FileSystemMock) Remove(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FileSystemMock_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type FileSystemMock_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - path string
func (_e *FileSystemMock_Expecter) Remove(path interface{}) *FileSystemMock_Remove_Call {
	return &FileSystemMock_Remove_Call{Call: _e.mock.On("Remove", path)}
}

func (_c *FileSystemMock_Remove_Call) Run(run func(path string)) *FileSystemMock_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FileSystemMock_Remove_Call) Return(err error) *FileSystemMock_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FileSystemMock_Remove_Call) RunAndReturn(run func(path string) error) *FileSystemMock_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type FileSystemMock
func (_mock *FileSystemMock) Rename(oldpath string, newpath string) error {
	ret := _mock.Called(oldpath, newpath)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(oldpath, newpath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FileSystemMock_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type FileSystemMock_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - oldpath string
//   - newpath string
func (_e *FileSystemMock_Expecter) Rename(oldpath interface{}, newpath interface{}) *FileSystemMock_Rename_Call {
	return &FileSystemMock_Rename_Call{Call: _e.mock.On("Rename", oldpath, newpath)}
}

func (_c *FileSystemMock_Rename_Call) Run(run func(oldpath string, newpath string)) *FileSystemMock_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FileSystemMock_Rename_Call) Return(err error) *FileSystemMock_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FileSystemMock_Rename_Call) RunAndReturn(run func(oldpath string, newpath string) error) *FileSystemMock_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type FileSystemMock
func (_mock *FileSystemMock) Stat(path string) (os.FileInfo, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (os.FileInfo, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FileSystemMock_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type FileSystemMock_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - path string
func (_e *FileSystemMock_Expecter) Stat(path interface{}) *FileSystemMock_Stat_Call {
	return &FileSystemMock_Stat_Call{Call: _e.mock.On("Stat", path)}
}

func (_c *FileSystemMock_Stat_Call) Run(run func(path string)) *FileSystemMock_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FileSystemMock_Stat_Call) Return(v os.FileInfo, err error) *FileSystemMock_Stat_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *FileSystemMock_Stat_Call) RunAndReturn(run func(path string) (os.FileInfo, error)) *FileSystemMock_Stat_Call {
	_c.Call.Return(run)
	return _c
}
