// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMediaConverterMock creates a new instance of MediaConverterMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaConverterMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaConverterMock {
	mock := &MediaConverterMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MediaConverterMock is an autogenerated mock type for the MediaConverter type
type MediaConverterMock struct {
	mock.Mock
}

type MediaConverterMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MediaConverterMock) EXPECT() *MediaConverterMock_Expecter {
	return &MediaConverterMock_Expecter{mock: &_m.Mock}
}

// Convert provides a mock function for the type MediaConverterMock
func (_mock *MediaConverterMock) Convert(inputPath string, outputDir string, id string) (string, string, error) {
	ret := _mock.Called(inputPath, outputDir, id)

	if len(ret) == 0 {
		panic("no return value specified for Convert")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (string, string, error)); ok {
		return returnFunc(inputPath, outputDir, id)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = returnFunc(inputPath, outputDir, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) string); ok {
		r1 = returnFunc(inputPath, outputDir, id)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string, string, string) error); ok {
		r2 = returnFunc(inputPath, outputDir, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MediaConverterMock_Convert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Convert'
type MediaConverterMock_Convert_Call struct {
	*mock.Call
}

// Convert is a helper method to define mock.On call
//   - inputPath string
//   - outputDir string
//   - id string
func (_e *MediaConverterMock_Expecter) Convert(inputPath interface{}, outputDir interface{}, id interface{}) *MediaConverterMock_Convert_Call {
	return &MediaConverterMock_Convert_Call{Call: _e.mock.On("Convert", inputPath, outputDir, id)}
}

func (_c *MediaConverterMock_Convert_Call) Run(run func(inputPath string, outputDir string, id string)) *MediaConverterMock_Convert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MediaConverterMock_Convert_Call) Return(outputPath string, codec string, err error) *MediaConverterMock_Convert_Call {
	_c.Call.Return(outputPath, codec, err)
	return _c
}

func (_c *MediaConverterMock_Convert_Call) RunAndReturn(run func(inputPath string, outputDir string, id string) (string, string, error)) *MediaConverterMock_Convert_Call {
	_c.Call.Return(run)
	return _c
}

// Probe provides a mock function for the type MediaConverterMock
func (_mock *MediaConverterMock) Probe(inputPath string) (int, int, error) {
	ret := _mock.Called(inputPath)

	if len(ret) == 0 {
		panic("no return value specified for Probe")
	}

	var r0 int
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (int, int, error)); ok {
		return returnFunc(inputPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(inputPath)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string) int); ok {
		r1 = returnFunc(inputPath)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(inputPath)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MediaConverterMock_Probe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Probe'
type MediaConverterMock_Probe_Call struct {
	*mock.Call
}

// Probe is a helper method to define mock.On call
//   - inputPath string
func (_e *MediaConverterMock_Expecter) Probe(inputPath interface{}) *MediaConverterMock_Probe_Call {
	return &MediaConverterMock_Probe_Call{Call: _e.mock.On("Probe", inputPath)}
}

func (_c *MediaConverterMock_Probe_Call) Run(run func(inputPath string)) *MediaConverterMock_Probe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MediaConverterMock_Probe_Call) Return(width int, height int, err error) *MediaConverterMock_Probe_Call {
	_c.Call.Return(width, height, err)
	return _c
}

func (_c *MediaConverterMock_Probe_Call) RunAndReturn(run func(inputPath string) (int, int, error)) *MediaConverterMock_Probe_Call {
	_c.Call.Return(run)
	return _c
}

// Thumbnail provides a mock function for the type MediaConverterMock
func (_mock *MediaConverterMock) Thumbnail(inputPath string, outputPath string) error {
	ret := _mock.Called(inputPath, outputPath)

	if len(ret) == 0 {
		panic("no return value specified for Thumbnail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(inputPath, outputPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MediaConverterMock_Thumbnail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Thumbnail'
type MediaConverterMock_Thumbnail_Call struct {
	*mock.Call
}

// Thumbnail is a helper method to define mock.On call
//   - inputPath string
//   - outputPath string
func (_e *MediaConverterMock_Expecter) Thumbnail(inputPath interface{}, outputPath interface{}) *MediaConverterMock_Thumbnail_Call {
	return &MediaConverterMock_Thumbnail_Call{Call: _e.mock.On("Thumbnail", inputPath, outputPath)}
}

func (_c *MediaConverterMock_Thumbnail_Call) Run(run func(inputPath string, outputPath string)) *MediaConverterMock_Thumbnail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MediaConverterMock_Thumbnail_Call) Return(err error) *MediaConverterMock_Thumbnail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MediaConverterMock_Thumbnail_Call) RunAndReturn(run func(inputPath string, outputPath string) error) *MediaConverterMock_Thumbnail_Call {
	_c.Call.Return(run)
	return _c
}
