// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/bnema/sharm/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewUploadStoreMock creates a new instance of UploadStoreMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUploadStoreMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UploadStoreMock {
	mock := &UploadStoreMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UploadStoreMock is an autogenerated mock type for the UploadStore type
type UploadStoreMock struct {
	mock.Mock
}

type UploadStoreMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UploadStoreMock) EXPECT() *UploadStoreMock_Expecter {
	return &UploadStoreMock_Expecter{mock: &_m.Mock}
}

// ClaimUploadAssetFinalization provides a mock function for the type UploadStoreMock
func (_mock *UploadStoreMock) ClaimUploadAssetFinalization(id string, now time.Time) (bool, error) {
	ret := _mock.Called(id, now)

	if len(ret) == 0 {
		panic("no return value specified for ClaimUploadAssetFinalization")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, time.Time) (bool, error)); ok {
		return returnFunc(id, now)
	}
	if returnFunc, ok := ret.Get(0).(func(string, time.Time) bool); ok {
		r0 = returnFunc(id, now)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = returnFunc(id, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UploadStoreMock_ClaimUploadAssetFinalization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimUploadAssetFinalization'
type UploadStoreMock_ClaimUploadAssetFinalization_Call struct {
	*mock.Call
}

// ClaimUploadAssetFinalization is a helper method to define mock.On call
//   - id string
//   - now time.Time
func (_e *UploadStoreMock_Expecter) ClaimUploadAssetFinalization(id any, now any) *UploadStoreMock_ClaimUploadAssetFinalization_Call {
	return &UploadStoreMock_ClaimUploadAssetFinalization_Call{Call: _e.mock.On("ClaimUploadAssetFinalization", id, now)}
}

func (_c *UploadStoreMock_ClaimUploadAssetFinalization_Call) Run(run func(id string, now time.Time)) *UploadStoreMock_ClaimUploadAssetFinalization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UploadStoreMock_ClaimUploadAssetFinalization_Call) Return(b bool, err error) *UploadStoreMock_ClaimUploadAssetFinalization_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *UploadStoreMock_ClaimUploadAssetFinalization_Call) RunAndReturn(run func(id string, now time.Time) (bool, error)) *UploadStoreMock_ClaimUploadAssetFinalization_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteUploadAsset provides a mock function for the type UploadStoreMock
func (_mock *UploadStoreMock) CompleteUploadAsset(id string, path string, sha256 string, receivedBytes int64, completedAt time.Time) error {
	ret := _mock.Called(id, path, sha256, receivedBytes, completedAt)

	if len(ret) == 0 {
		panic("no return value specified for CompleteUploadAsset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, int64, time.Time) error); ok {
		r0 = returnFunc(id, path, sha256, receivedBytes, completedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UploadStoreMock_CompleteUploadAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteUploadAsset'
type UploadStoreMock_CompleteUploadAsset_Call struct {
	*mock.Call
}

// CompleteUploadAsset is a helper method to define mock.On call
//   - id string
//   - path string
//   - sha256 string
//   - receivedBytes int64
//   - completedAt time.Time
func (_e *UploadStoreMock_Expecter) CompleteUploadAsset(id any, path any, sha256 any, receivedBytes any, completedAt any) *UploadStoreMock_CompleteUploadAsset_Call {
	return &UploadStoreMock_CompleteUploadAsset_Call{Call: _e.mock.On("CompleteUploadAsset", id, path, sha256, receivedBytes, completedAt)}
}

func (_c *UploadStoreMock_CompleteUploadAsset_Call) Run(run func(id string, path string, sha256 string, receivedBytes int64, completedAt time.Time)) *UploadStoreMock_CompleteUploadAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *UploadStoreMock_CompleteUploadAsset_Call) Return(err error) *UploadStoreMock_CompleteUploadAsset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UploadStoreMock_CompleteUploadAsset_Call) RunAndReturn(run func(id string, path string, sha256 string, receivedBytes int64, completedAt time.Time) error) *UploadStoreMock_CompleteUploadAsset_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUploadSession provides a mock function for the type UploadStoreMock
func (_mock *UploadStoreMock) CreateUploadSession(session *domain.UploadSession, assets []domain.UploadAsset, maxReservedBytes int64) error {
	ret := _mock.Called(session, assets, maxReservedBytes)

	if len(ret) == 0 {
		panic("no return value specified for CreateUploadSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.UploadSession, []domain.UploadAsset, int64) error); ok {
		r0 = returnFunc(session, assets, maxReservedBytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UploadStoreMock_CreateUploadSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUploadSession'
type UploadStoreMock_CreateUploadSession_Call struct {
	*mock.Call
}

// CreateUploadSession is a helper method to define mock.On call
//   - session *domain.UploadSession
//   - assets []domain.UploadAsset
//   - maxReservedBytes int64
func (_e *UploadStoreMock_Expecter) CreateUploadSession(session any, assets any, maxReservedBytes any) *UploadStoreMock_CreateUploadSession_Call {
	return &UploadStoreMock_CreateUploadSession_Call{Call: _e.mock.On("CreateUploadSession", session, assets, maxReservedBytes)}
}

func (_c *UploadStoreMock_CreateUploadSession_Call) Run(run func(session *domain.UploadSession, assets []domain.UploadAsset, maxReservedBytes int64)) *UploadStoreMock_CreateUploadSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.UploadSession
		if args[0] != nil {
			arg0 = args[0].(*domain.UploadSession)
		}
		var arg1 []domain.UploadAsset
		if args[1] != nil {
			arg1 = args[1].([]domain.UploadAsset)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UploadStoreMock_CreateUploadSession_Call) Return(err error) *UploadStoreMock_CreateUploadSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UploadStoreMock_CreateUploadSession_Call) RunAndReturn(run func(session *domain.UploadSession, assets []domain.UploadAsset, maxReservedBytes int64) error) *UploadStoreMock_CreateUploadSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUploadSession provides a mock function for the type UploadStoreMock
func (_mock *UploadStoreMock) DeleteUploadSession(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUploadSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UploadStoreMock_DeleteUploadSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUploadSession'
type UploadStoreMock_DeleteUploadSession_Call struct {
	*mock.Call
}

// DeleteUploadSession is a helper method to define mock.On call
//   - id string
func (_e *UploadStoreMock_Expecter) DeleteUploadSession(id any) *UploadStoreMock_DeleteUploadSession_Call {
	return &UploadStoreMock_DeleteUploadSession_Call{Call: _e.mock.On("DeleteUploadSession", id)}
}

func (_c *UploadStoreMock_DeleteUploadSession_Call) Run(run func(id string)) *UploadStoreMock_DeleteUploadSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UploadStoreMock_DeleteUploadSession_Call) Return(err error) *UploadStoreMock_DeleteUploadSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UploadStoreMock_DeleteUploadSession_Call) RunAndReturn(run func(id string) error) *UploadStoreMock_DeleteUploadSession_Call {
	_c.Call.Return(run)
	return _c
}

// FailUploadAsset provides a mock function for the type UploadStoreMock
func (_mock *UploadStoreMock) FailUploadAsset(id string, errMsg string, now time.Time) error {
	ret := _mock.Called(id, errMsg, now)

	if len(ret) == 0 {
		panic("no return value specified for FailUploadAsset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, time.Time) error); ok {
		r0 = returnFunc(id, errMsg, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UploadStoreMock_FailUploadAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailUploadAsset'
type UploadStoreMock_FailUploadAsset_Call struct {
	*mock.Call
}

// FailUploadAsset is a helper method to define mock.On call
//   - id string
//   - errMsg string
//   - now time.Time
func (_e *UploadStoreMock_Expecter) FailUploadAsset(id any, errMsg any, now any) *UploadStoreMock_FailUploadAsset_Call {
	return &UploadStoreMock_FailUploadAsset_Call{Call: _e.mock.On("FailUploadAsset", id, errMsg, now)}
}

func (_c *UploadStoreMock_FailUploadAsset_Call) Run(run func(id string, errMsg string, now time.Time)) *UploadStoreMock_FailUploadAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UploadStoreMock_FailUploadAsset_Call) Return(err error) *UploadStoreMock_FailUploadAsset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UploadStoreMock_FailUploadAsset_Call) RunAndReturn(run func(id string, errMsg string, now time.Time) error) *UploadStoreMock_FailUploadAsset_Call {
	_c.Call.Return(run)
	return _c
}

// GetUploadAsset provides a mock function for the type UploadStoreMock
func (_mock *UploadStoreMock) GetUploadAsset(id string) (*domain.UploadAsset, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUploadAsset")
	}

	var r0 *domain.UploadAsset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.UploadAsset, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.UploadAsset); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UploadAsset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UploadStoreMock_GetUploadAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUploadAsset'
type UploadStoreMock_GetUploadAsset_Call struct {
	*mock.Call
}

// GetUploadAsset is a helper method to define mock.On call
//   - id string
func (_e *UploadStoreMock_Expecter) GetUploadAsset(id any) *UploadStoreMock_GetUploadAsset_Call {
	return &UploadStoreMock_GetUploadAsset_Call{Call: _e.mock.On("GetUploadAsset", id)}
}

func (_c *UploadStoreMock_GetUploadAsset_Call) Run(run func(id string)) *UploadStoreMock_GetUploadAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UploadStoreMock_GetUploadAsset_Call) Return(uploadAsset *domain.UploadAsset, err error) *UploadStoreMock_GetUploadAsset_Call {
	_c.Call.Return(uploadAsset, err)
	return _c
}

func (_c *UploadStoreMock_GetUploadAsset_Call) RunAndReturn(run func(id string) (*domain.UploadAsset, error)) *UploadStoreMock_GetUploadAsset_Call {
	_c.Call.Return(run)
	return _c
}

// GetUploadSession provides a mock function for the type UploadStoreMock
func (_mock *UploadStoreMock) GetUploadSession(id string) (*domain.UploadSession, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUploadSession")
	}

	var r0 *domain.UploadSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.UploadSession, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.UploadSession); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UploadSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UploadStoreMock_GetUploadSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUploadSession'
type UploadStoreMock_GetUploadSession_Call struct {
	*mock.Call
}

// GetUploadSession is a helper method to define mock.On call
//   - id string
func (_e *UploadStoreMock_Expecter) GetUploadSession(id any) *UploadStoreMock_GetUploadSession_Call {
	return &UploadStoreMock_GetUploadSession_Call{Call: _e.mock.On("GetUploadSession", id)}
}

func (_c *UploadStoreMock_GetUploadSession_Call) Run(run func(id string)) *UploadStoreMock_GetUploadSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UploadStoreMock_GetUploadSession_Call) Return(uploadSession *domain.UploadSession, err error) *UploadStoreMock_GetUploadSession_Call {
	_c.Call.Return(uploadSession, err)
	return _c
}

func (_c *UploadStoreMock_GetUploadSession_Call) RunAndReturn(run func(id string) (*domain.UploadSession, error)) *UploadStoreMock_GetUploadSession_Call {
	_c.Call.Return(run)
	return _c
}

// ListExpiredUploadSessions provides a mock function for the type UploadStoreMock
func (_mock *UploadStoreMock) ListExpiredUploadSessions(now time.Time) ([]domain.UploadSession, error) {
	ret := _mock.Called(now)

	if len(ret) == 0 {
		panic("no return value specified for ListExpiredUploadSessions")
	}

	var r0 []domain.UploadSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) ([]domain.UploadSession, error)); ok {
		return returnFunc(now)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time) []domain.UploadSession); ok {
		r0 = returnFunc(now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UploadSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = returnFunc(now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UploadStoreMock_ListExpiredUploadSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExpiredUploadSessions'
type UploadStoreMock_ListExpiredUploadSessions_Call struct {
	*mock.Call
}

// ListExpiredUploadSessions is a helper method to define mock.On call
//   - now time.Time
func (_e *UploadStoreMock_Expecter) ListExpiredUploadSessions(now any) *UploadStoreMock_ListExpiredUploadSessions_Call {
	return &UploadStoreMock_ListExpiredUploadSessions_Call{Call: _e.mock.On("ListExpiredUploadSessions", now)}
}

func (_c *UploadStoreMock_ListExpiredUploadSessions_Call) Run(run func(now time.Time)) *UploadStoreMock_ListExpiredUploadSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UploadStoreMock_ListExpiredUploadSessions_Call) Return(uploadSessions []domain.UploadSession, err error) *UploadStoreMock_ListExpiredUploadSessions_Call {
	_c.Call.Return(uploadSessions, err)
	return _c
}

func (_c *UploadStoreMock_ListExpiredUploadSessions_Call) RunAndReturn(run func(now time.Time) ([]domain.UploadSession, error)) *UploadStoreMock_ListExpiredUploadSessions_Call {
	_c.Call.Return(run)
	return _c
}

// ListUploadChunks provides a mock function for the type UploadStoreMock
func (_mock *UploadStoreMock) ListUploadChunks(assetID string) ([]domain.UploadChunk, error) {
	ret := _mock.Called(assetID)

	if len(ret) == 0 {
		panic("no return value specified for ListUploadChunks")
	}

	var r0 []domain.UploadChunk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]domain.UploadChunk, error)); ok {
		return returnFunc(assetID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []domain.UploadChunk); ok {
		r0 = returnFunc(assetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UploadChunk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(assetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UploadStoreMock_ListUploadChunks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUploadChunks'
type UploadStoreMock_ListUploadChunks_Call struct {
	*mock.Call
}

// ListUploadChunks is a helper method to define mock.On call
//   - assetID string
func (_e *UploadStoreMock_Expecter) ListUploadChunks(assetID any) *UploadStoreMock_ListUploadChunks_Call {
	return &UploadStoreMock_ListUploadChunks_Call{Call: _e.mock.On("ListUploadChunks", assetID)}
}

func (_c *UploadStoreMock_ListUploadChunks_Call) Run(run func(assetID string)) *UploadStoreMock_ListUploadChunks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UploadStoreMock_ListUploadChunks_Call) Return(uploadChunks []domain.UploadChunk, err error) *UploadStoreMock_ListUploadChunks_Call {
	_c.Call.Return(uploadChunks, err)
	return _c
}

func (_c *UploadStoreMock_ListUploadChunks_Call) RunAndReturn(run func(assetID string) ([]domain.UploadChunk, error)) *UploadStoreMock_ListUploadChunks_Call {
	_c.Call.Return(run)
	return _c
}

// RecordUploadChunk provides a mock function for the type UploadStoreMock
func (_mock *UploadStoreMock) RecordUploadChunk(assetID string, chunk *domain.UploadChunk) (bool, error) {
	ret := _mock.Called(assetID, chunk)

	if len(ret) == 0 {
		panic("no return value specified for RecordUploadChunk")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *domain.UploadChunk) (bool, error)); ok {
		return returnFunc(assetID, chunk)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *domain.UploadChunk) bool); ok {
		r0 = returnFunc(assetID, chunk)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, *domain.UploadChunk) error); ok {
		r1 = returnFunc(assetID, chunk)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UploadStoreMock_RecordUploadChunk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordUploadChunk'
type UploadStoreMock_RecordUploadChunk_Call struct {
	*mock.Call
}

// RecordUploadChunk is a helper method to define mock.On call
//   - assetID string
//   - chunk *domain.UploadChunk
func (_e *UploadStoreMock_Expecter) RecordUploadChunk(assetID any, chunk any) *UploadStoreMock_RecordUploadChunk_Call {
	return &UploadStoreMock_RecordUploadChunk_Call{Call: _e.mock.On("RecordUploadChunk", assetID, chunk)}
}

func (_c *UploadStoreMock_RecordUploadChunk_Call) Run(run func(assetID string, chunk *domain.UploadChunk)) *UploadStoreMock_RecordUploadChunk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *domain.UploadChunk
		if args[1] != nil {
			arg1 = args[1].(*domain.UploadChunk)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UploadStoreMock_RecordUploadChunk_Call) Return(inserted bool, err error) *UploadStoreMock_RecordUploadChunk_Call {
	_c.Call.Return(inserted, err)
	return _c
}

func (_c *UploadStoreMock_RecordUploadChunk_Call) RunAndReturn(run func(assetID string, chunk *domain.UploadChunk) (bool, error)) *UploadStoreMock_RecordUploadChunk_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseUploadAssetFinalization provides a mock function for the type UploadStoreMock
func (_mock *UploadStoreMock) ReleaseUploadAssetFinalization(id string, errMsg string, now time.Time) error {
	ret := _mock.Called(id, errMsg, now)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseUploadAssetFinalization")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, time.Time) error); ok {
		r0 = returnFunc(id, errMsg, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UploadStoreMock_ReleaseUploadAssetFinalization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseUploadAssetFinalization'
type UploadStoreMock_ReleaseUploadAssetFinalization_Call struct {
	*mock.Call
}

// ReleaseUploadAssetFinalization is a helper method to define mock.On call
//   - id string
//   - errMsg string
//   - now time.Time
func (_e *UploadStoreMock_Expecter) ReleaseUploadAssetFinalization(id any, errMsg any, now any) *UploadStoreMock_ReleaseUploadAssetFinalization_Call {
	return &UploadStoreMock_ReleaseUploadAssetFinalization_Call{Call: _e.mock.On("ReleaseUploadAssetFinalization", id, errMsg, now)}
}

func (_c *UploadStoreMock_ReleaseUploadAssetFinalization_Call) Run(run func(id string, errMsg string, now time.Time)) *UploadStoreMock_ReleaseUploadAssetFinalization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UploadStoreMock_ReleaseUploadAssetFinalization_Call) Return(err error) *UploadStoreMock_ReleaseUploadAssetFinalization_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UploadStoreMock_ReleaseUploadAssetFinalization_Call) RunAndReturn(run func(id string, errMsg string, now time.Time) error) *UploadStoreMock_ReleaseUploadAssetFinalization_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUploadSessionStatus provides a mock function for the type UploadStoreMock
func (_mock *UploadStoreMock) UpdateUploadSessionStatus(id string, status domain.UploadSessionStatus, now time.Time) error {
	ret := _mock.Called(id, status, now)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUploadSessionStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, domain.UploadSessionStatus, time.Time) error); ok {
		r0 = returnFunc(id, status, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UploadStoreMock_UpdateUploadSessionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUploadSessionStatus'
type UploadStoreMock_UpdateUploadSessionStatus_Call struct {
	*mock.Call
}

// UpdateUploadSessionStatus is a helper method to define mock.On call
//   - id string
//   - status domain.UploadSessionStatus
//   - now time.Time
func (_e *UploadStoreMock_Expecter) UpdateUploadSessionStatus(id any, status any, now any) *UploadStoreMock_UpdateUploadSessionStatus_Call {
	return &UploadStoreMock_UpdateUploadSessionStatus_Call{Call: _e.mock.On("UpdateUploadSessionStatus", id, status, now)}
}

func (_c *UploadStoreMock_UpdateUploadSessionStatus_Call) Run(run func(id string, status domain.UploadSessionStatus, now time.Time)) *UploadStoreMock_UpdateUploadSessionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 domain.UploadSessionStatus
		if args[1] != nil {
			arg1 = args[1].(domain.UploadSessionStatus)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UploadStoreMock_UpdateUploadSessionStatus_Call) Return(err error) *UploadStoreMock_UpdateUploadSessionStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UploadStoreMock_UpdateUploadSessionStatus_Call) RunAndReturn(run func(id string, status domain.UploadSessionStatus, now time.Time) error) *UploadStoreMock_UpdateUploadSessionStatus_Call {
	_c.Call.Return(run)
	return _c
}
