// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/sharm/internal/port"
	mock "github.com/stretchr/testify/mock"
)

// NewEventSubscriberMock creates a new instance of EventSubscriberMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventSubscriberMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventSubscriberMock {
	mock := &EventSubscriberMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EventSubscriberMock is an autogenerated mock type for the EventSubscriber type
type EventSubscriberMock struct {
	mock.Mock
}

type EventSubscriberMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EventSubscriberMock) EXPECT() *EventSubscriberMock_Expecter {
	return &EventSubscriberMock_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function for the type EventSubscriberMock
func (_mock *EventSubscriberMock) Subscribe(mediaID string) chan port.Event {
	ret := _mock.Called(mediaID)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 chan port.Event
	if returnFunc, ok := ret.Get(0).(func(string) chan port.Event); ok {
		r0 = returnFunc(mediaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan port.Event)
		}
	}
	return r0
}

// EventSubscriberMock_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type EventSubscriberMock_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - mediaID string
func (_e *EventSubscriberMock_Expecter) Subscribe(mediaID any) *EventSubscriberMock_Subscribe_Call {
	return &EventSubscriberMock_Subscribe_Call{Call: _e.mock.On("Subscribe", mediaID)}
}

func (_c *EventSubscriberMock_Subscribe_Call) Run(run func(mediaID string)) *EventSubscriberMock_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EventSubscriberMock_Subscribe_Call) Return(eventCh chan port.Event) *EventSubscriberMock_Subscribe_Call {
	_c.Call.Return(eventCh)
	return _c
}

func (_c *EventSubscriberMock_Subscribe_Call) RunAndReturn(run func(mediaID string) chan port.Event) *EventSubscriberMock_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function for the type EventSubscriberMock
func (_mock *EventSubscriberMock) Unsubscribe(mediaID string, ch chan port.Event) {
	_mock.Called(mediaID, ch)
	return
}

// EventSubscriberMock_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type EventSubscriberMock_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - mediaID string
//   - ch chan port.Event
func (_e *EventSubscriberMock_Expecter) Unsubscribe(mediaID any, ch any) *EventSubscriberMock_Unsubscribe_Call {
	return &EventSubscriberMock_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", mediaID, ch)}
}

func (_c *EventSubscriberMock_Unsubscribe_Call) Run(run func(mediaID string, ch chan port.Event)) *EventSubscriberMock_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 chan port.Event
		if args[1] != nil {
			arg1 = args[1].(chan port.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EventSubscriberMock_Unsubscribe_Call) Return() *EventSubscriberMock_Unsubscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventSubscriberMock_Unsubscribe_Call) RunAndReturn(run func(mediaID string, ch chan port.Event)) *EventSubscriberMock_Unsubscribe_Call {
	_c.Run(run)
	return _c
}
