// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/sharm/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMediaStoreMock creates a new instance of MediaStoreMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaStoreMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaStoreMock {
	mock := &MediaStoreMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MediaStoreMock is an autogenerated mock type for the MediaStore type
type MediaStoreMock struct {
	mock.Mock
}

type MediaStoreMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MediaStoreMock) EXPECT() *MediaStoreMock_Expecter {
	return &MediaStoreMock_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MediaStoreMock
func (_mock *MediaStoreMock) Delete(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MediaStoreMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MediaStoreMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MediaStoreMock_Expecter) Delete(id interface{}) *MediaStoreMock_Delete_Call {
	return &MediaStoreMock_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MediaStoreMock_Delete_Call) Run(run func(id string)) *MediaStoreMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MediaStoreMock_Delete_Call) Return(err error) *MediaStoreMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MediaStoreMock_Delete_Call) RunAndReturn(run func(id string) error) *MediaStoreMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MediaStoreMock
func (_mock *MediaStoreMock) Get(id string) (*domain.Media, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.Media, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.Media); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MediaStoreMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MediaStoreMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *MediaStoreMock_Expecter) Get(id interface{}) *MediaStoreMock_Get_Call {
	return &MediaStoreMock_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MediaStoreMock_Get_Call) Run(run func(id string)) *MediaStoreMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MediaStoreMock_Get_Call) Return(media *domain.Media, err error) *MediaStoreMock_Get_Call {
	_c.Call.Return(media, err)
	return _c
}

func (_c *MediaStoreMock_Get_Call) RunAndReturn(run func(id string) (*domain.Media, error)) *MediaStoreMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListExpired provides a mock function for the type MediaStoreMock
func (_mock *MediaStoreMock) ListExpired() ([]*domain.Media, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListExpired")
	}

	var r0 []*domain.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*domain.Media, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*domain.Media); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MediaStoreMock_ListExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExpired'
type MediaStoreMock_ListExpired_Call struct {
	*mock.Call
}

// ListExpired is a helper method to define mock.On call
func (_e *MediaStoreMock_Expecter) ListExpired() *MediaStoreMock_ListExpired_Call {
	return &MediaStoreMock_ListExpired_Call{Call: _e.mock.On("ListExpired")}
}

func (_c *MediaStoreMock_ListExpired_Call) Run(run func()) *MediaStoreMock_ListExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MediaStoreMock_ListExpired_Call) Return(medias []*domain.Media, err error) *MediaStoreMock_ListExpired_Call {
	_c.Call.Return(medias, err)
	return _c
}

func (_c *MediaStoreMock_ListExpired_Call) RunAndReturn(run func() ([]*domain.Media, error)) *MediaStoreMock_ListExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MediaStoreMock
func (_mock *MediaStoreMock) Save(m *domain.Media) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.Media) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MediaStoreMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MediaStoreMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - m *domain.Media
func (_e *MediaStoreMock_Expecter) Save(m interface{}) *MediaStoreMock_Save_Call {
	return &MediaStoreMock_Save_Call{Call: _e.mock.On("Save", m)}
}

func (_c *MediaStoreMock_Save_Call) Run(run func(m *domain.Media)) *MediaStoreMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.Media
		if args[0] != nil {
			arg0 = args[0].(*domain.Media)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MediaStoreMock_Save_Call) Return(err error) *MediaStoreMock_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MediaStoreMock_Save_Call) RunAndReturn(run func(m *domain.Media) error) *MediaStoreMock_Save_Call {
	_c.Call.Return(run)
	return _c
}
