// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package sqlitedb

import (
	"context"
	"time"
)

const deleteJobsByMedia = `-- name: DeleteJobsByMedia :exec
DELETE FROM jobs WHERE media_id = ?
`

func (q *Queries) DeleteJobsByMedia(ctx context.Context, mediaID string) error {
	_, err := q.db.ExecContext(ctx, deleteJobsByMedia, mediaID)
	return err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media WHERE id = ?
`

func (q *Queries) DeleteMedia(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMedia, id)
	return err
}

const getMedia = `-- name: GetMedia :one
SELECT id, type, original_name, original_path, converted_path, status, codec, error_message, retention_days, file_size, width, height, thumb_path, created_at, expires_at, probe_json FROM media WHERE id = ? LIMIT 1
`

func (q *Queries) GetMedia(ctx context.Context, id string) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OriginalName,
		&i.OriginalPath,
		&i.ConvertedPath,
		&i.Status,
		&i.Codec,
		&i.ErrorMessage,
		&i.RetentionDays,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.ThumbPath,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ProbeJson,
	)
	return i, err
}

const insertMedia = `-- name: InsertMedia :exec
INSERT INTO media (
    id, type, original_name, original_path, converted_path,
    status, codec, error_message, retention_days, file_size,
    width, height, thumb_path, created_at, expires_at, probe_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMediaParams struct {
	ID            string
	Type          string
	OriginalName  string
	OriginalPath  string
	ConvertedPath string
	Status        string
	Codec         string
	ErrorMessage  string
	RetentionDays int64
	FileSize      int64
	Width         int64
	Height        int64
	ThumbPath     string
	CreatedAt     time.Time
	ExpiresAt     time.Time
	ProbeJson     string
}

func (q *Queries) InsertMedia(ctx context.Context, arg InsertMediaParams) error {
	_, err := q.db.ExecContext(ctx, insertMedia,
		arg.ID,
		arg.Type,
		arg.OriginalName,
		arg.OriginalPath,
		arg.ConvertedPath,
		arg.Status,
		arg.Codec,
		arg.ErrorMessage,
		arg.RetentionDays,
		arg.FileSize,
		arg.Width,
		arg.Height,
		arg.ThumbPath,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ProbeJson,
	)
	return err
}

const listAllMedia = `-- name: ListAllMedia :many
SELECT id, type, original_name, original_path, converted_path, status, codec, error_message, retention_days, file_size, width, height, thumb_path, created_at, expires_at, probe_json FROM media ORDER BY created_at DESC
`

func (q *Queries) ListAllMedia(ctx context.Context) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listAllMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.OriginalName,
			&i.OriginalPath,
			&i.ConvertedPath,
			&i.Status,
			&i.Codec,
			&i.ErrorMessage,
			&i.RetentionDays,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ProbeJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredMedia = `-- name: ListExpiredMedia :many
SELECT id, type, original_name, original_path, converted_path, status, codec, error_message, retention_days, file_size, width, height, thumb_path, created_at, expires_at, probe_json FROM media WHERE expires_at < datetime('now')
`

func (q *Queries) ListExpiredMedia(ctx context.Context) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.OriginalName,
			&i.OriginalPath,
			&i.ConvertedPath,
			&i.Status,
			&i.Codec,
			&i.ErrorMessage,
			&i.RetentionDays,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ProbeJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByStatus = `-- name: ListMediaByStatus :many
SELECT id, type, original_name, original_path, converted_path, status, codec, error_message, retention_days, file_size, width, height, thumb_path, created_at, expires_at, probe_json FROM media WHERE status = ? ORDER BY created_at DESC
`

func (q *Queries) ListMediaByStatus(ctx context.Context, status string) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listMediaByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.OriginalName,
			&i.OriginalPath,
			&i.ConvertedPath,
			&i.Status,
			&i.Codec,
			&i.ErrorMessage,
			&i.RetentionDays,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.ThumbPath,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ProbeJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaDone = `-- name: UpdateMediaDone :exec
UPDATE media SET
    status = 'done',
    converted_path = ?,
    codec = ?,
    width = ?,
    height = ?,
    thumb_path = ?,
    file_size = ?
WHERE id = ?
`

type UpdateMediaDoneParams struct {
	ConvertedPath string
	Codec         string
	Width         int64
	Height        int64
	ThumbPath     string
	FileSize      int64
	ID            string
}

func (q *Queries) UpdateMediaDone(ctx context.Context, arg UpdateMediaDoneParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaDone,
		arg.ConvertedPath,
		arg.Codec,
		arg.Width,
		arg.Height,
		arg.ThumbPath,
		arg.FileSize,
		arg.ID,
	)
	return err
}

const updateMediaProbeJSON = `-- name: UpdateMediaProbeJSON :exec
UPDATE media SET probe_json = ? WHERE id = ?
`

type UpdateMediaProbeJSONParams struct {
	ProbeJson string
	ID        string
}

func (q *Queries) UpdateMediaProbeJSON(ctx context.Context, arg UpdateMediaProbeJSONParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaProbeJSON, arg.ProbeJson, arg.ID)
	return err
}

const updateMediaStatus = `-- name: UpdateMediaStatus :exec
UPDATE media SET status = ?, error_message = ? WHERE id = ?
`

type UpdateMediaStatusParams struct {
	Status       string
	ErrorMessage string
	ID           string
}

func (q *Queries) UpdateMediaStatus(ctx context.Context, arg UpdateMediaStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMediaStatus, arg.Status, arg.ErrorMessage, arg.ID)
	return err
}
