// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"database/sql"
	"time"
)

type Job struct {
	ID           int64
	MediaID      string
	Type         string
	Status       string
	ErrorMessage string
	Attempts     int64
	CreatedAt    time.Time
	StartedAt    sql.NullTime
	CompletedAt  sql.NullTime
	Codec        string
	Fps          int64
	Progress     int64
	LeaseUntil   sql.NullTime
	HeartbeatAt  sql.NullTime
	MaxAttempts  int64
}

type MediaAsset struct {
	ID           string
	MediaID      string
	Role         string
	Filename     string
	Path         string
	SizeBytes    int64
	Sha256       string
	Status       string
	ErrorMessage string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MediaVariant struct {
	ID              int64
	MediaID         string
	Codec           string
	Path            string
	FileSize        int64
	Width           int64
	Height          int64
	Status          string
	ErrorMessage    string
	CreatedAt       time.Time
	Container       string
	VideoCodec      string
	AudioCodec      string
	HasAudio        int64
	Profile         string
	Level           string
	MimeType        string
	Origin          string
	IsPrimary       int64
	Progress        int64
	DurationSeconds float64
}

type Medium struct {
	ID            string
	Type          string
	OriginalName  string
	OriginalPath  string
	ConvertedPath string
	Status        string
	Codec         string
	ErrorMessage  string
	RetentionDays int64
	FileSize      int64
	Width         int64
	Height        int64
	ThumbPath     string
	CreatedAt     time.Time
	ExpiresAt     time.Time
	ProbeJson     string
}

type UploadAsset struct {
	ID             string
	SessionID      string
	MediaID        string
	Role           string
	Filename       string
	ExpectedSize   int64
	ChunkSize      int64
	TotalChunks    int64
	ReceivedBytes  int64
	ExpectedSha256 string
	Sha256         string
	Status         string
	Path           string
	ErrorMessage   string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    sql.NullTime
}

type UploadChunk struct {
	AssetID    string
	ChunkIndex int64
	SizeBytes  int64
	Sha256     string
	CreatedAt  time.Time
}

type UploadSession struct {
	ID            string
	MediaID       string
	UserID        int64
	Filename      string
	RetentionDays int64
	KeepOriginal  int64
	ExpectedBytes int64
	ReservedBytes int64
	Status        string
	ExpiresAt     time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID             int64
	Username       string
	PasswordHash   string
	CreatedAt      string
	UpdatedAt      string
	SessionVersion int64
}
