// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: uploads.sql

package sqlitedb

import (
	"context"
	"database/sql"
	"time"
)

const claimUploadAssetFinalization = `-- name: ClaimUploadAssetFinalization :execrows
UPDATE upload_assets SET status = 'finalizing', updated_at = ?
WHERE id = ? AND status = 'uploading'
`

type ClaimUploadAssetFinalizationParams struct {
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) ClaimUploadAssetFinalization(ctx context.Context, arg ClaimUploadAssetFinalizationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimUploadAssetFinalization, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeUploadAsset = `-- name: CompleteUploadAsset :execrows
UPDATE upload_assets SET
    received_bytes = ?,
    sha256 = ?,
    status = 'available',
    path = ?,
    error_message = '',
    updated_at = ?,
    completed_at = ?
WHERE id = ? AND status = 'finalizing'
`

type CompleteUploadAssetParams struct {
	ReceivedBytes int64
	Sha256        string
	Path          string
	UpdatedAt     time.Time
	CompletedAt   sql.NullTime
	ID            string
}

func (q *Queries) CompleteUploadAsset(ctx context.Context, arg CompleteUploadAssetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeUploadAsset,
		arg.ReceivedBytes,
		arg.Sha256,
		arg.Path,
		arg.UpdatedAt,
		arg.CompletedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUploadSession = `-- name: DeleteUploadSession :exec
DELETE FROM upload_sessions WHERE id = ?
`

func (q *Queries) DeleteUploadSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUploadSession, id)
	return err
}

const failUploadAsset = `-- name: FailUploadAsset :execrows
UPDATE upload_assets SET
    status = 'failed',
    error_message = ?,
    updated_at = ?
WHERE id = ? AND status IN ('uploading', 'finalizing')
`

type FailUploadAssetParams struct {
	ErrorMessage string
	UpdatedAt    time.Time
	ID           string
}

func (q *Queries) FailUploadAsset(ctx context.Context, arg FailUploadAssetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failUploadAsset, arg.ErrorMessage, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUploadAsset = `-- name: GetUploadAsset :one
SELECT id, session_id, media_id, role, filename, expected_size, chunk_size, total_chunks, received_bytes, expected_sha256, sha256, status, path, error_message, created_at, updated_at, completed_at FROM upload_assets WHERE id = ? LIMIT 1
`

func (q *Queries) GetUploadAsset(ctx context.Context, id string) (UploadAsset, error) {
	row := q.db.QueryRowContext(ctx, getUploadAsset, id)
	var i UploadAsset
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MediaID,
		&i.Role,
		&i.Filename,
		&i.ExpectedSize,
		&i.ChunkSize,
		&i.TotalChunks,
		&i.ReceivedBytes,
		&i.ExpectedSha256,
		&i.Sha256,
		&i.Status,
		&i.Path,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getUploadAssetBySessionAndRole = `-- name: GetUploadAssetBySessionAndRole :one
SELECT id, session_id, media_id, role, filename, expected_size, chunk_size, total_chunks, received_bytes, expected_sha256, sha256, status, path, error_message, created_at, updated_at, completed_at FROM upload_assets WHERE session_id = ? AND role = ? LIMIT 1
`

type GetUploadAssetBySessionAndRoleParams struct {
	SessionID string
	Role      string
}

func (q *Queries) GetUploadAssetBySessionAndRole(ctx context.Context, arg GetUploadAssetBySessionAndRoleParams) (UploadAsset, error) {
	row := q.db.QueryRowContext(ctx, getUploadAssetBySessionAndRole, arg.SessionID, arg.Role)
	var i UploadAsset
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MediaID,
		&i.Role,
		&i.Filename,
		&i.ExpectedSize,
		&i.ChunkSize,
		&i.TotalChunks,
		&i.ReceivedBytes,
		&i.ExpectedSha256,
		&i.Sha256,
		&i.Status,
		&i.Path,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getUploadAssetsBySession = `-- name: GetUploadAssetsBySession :many
SELECT id, session_id, media_id, role, filename, expected_size, chunk_size, total_chunks, received_bytes, expected_sha256, sha256, status, path, error_message, created_at, updated_at, completed_at FROM upload_assets WHERE session_id = ? ORDER BY created_at ASC
`

func (q *Queries) GetUploadAssetsBySession(ctx context.Context, sessionID string) ([]UploadAsset, error) {
	rows, err := q.db.QueryContext(ctx, getUploadAssetsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadAsset
	for rows.Next() {
		var i UploadAsset
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MediaID,
			&i.Role,
			&i.Filename,
			&i.ExpectedSize,
			&i.ChunkSize,
			&i.TotalChunks,
			&i.ReceivedBytes,
			&i.ExpectedSha256,
			&i.Sha256,
			&i.Status,
			&i.Path,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUploadChunk = `-- name: GetUploadChunk :one
SELECT asset_id, chunk_index, size_bytes, sha256, created_at FROM upload_chunks WHERE asset_id = ? AND chunk_index = ? LIMIT 1
`

type GetUploadChunkParams struct {
	AssetID    string
	ChunkIndex int64
}

func (q *Queries) GetUploadChunk(ctx context.Context, arg GetUploadChunkParams) (UploadChunk, error) {
	row := q.db.QueryRowContext(ctx, getUploadChunk, arg.AssetID, arg.ChunkIndex)
	var i UploadChunk
	err := row.Scan(
		&i.AssetID,
		&i.ChunkIndex,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadSession = `-- name: GetUploadSession :one
SELECT id, media_id, user_id, filename, retention_days, keep_original, expected_bytes, reserved_bytes, status, expires_at, created_at, updated_at FROM upload_sessions WHERE id = ? LIMIT 1
`

func (q *Queries) GetUploadSession(ctx context.Context, id string) (UploadSession, error) {
	row := q.db.QueryRowContext(ctx, getUploadSession, id)
	var i UploadSession
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.UserID,
		&i.Filename,
		&i.RetentionDays,
		&i.KeepOriginal,
		&i.ExpectedBytes,
		&i.ReservedBytes,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementUploadAssetReceived = `-- name: IncrementUploadAssetReceived :exec
UPDATE upload_assets SET
    received_bytes = received_bytes + ?,
    updated_at = ?
WHERE id = ? AND status = 'uploading'
`

type IncrementUploadAssetReceivedParams struct {
	ReceivedBytes int64
	UpdatedAt     time.Time
	ID            string
}

func (q *Queries) IncrementUploadAssetReceived(ctx context.Context, arg IncrementUploadAssetReceivedParams) error {
	_, err := q.db.ExecContext(ctx, incrementUploadAssetReceived, arg.ReceivedBytes, arg.UpdatedAt, arg.ID)
	return err
}

const insertUploadAsset = `-- name: InsertUploadAsset :exec
INSERT INTO upload_assets (
    id, session_id, media_id, role, filename, expected_size, chunk_size,
    total_chunks, expected_sha256, status, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertUploadAssetParams struct {
	ID             string
	SessionID      string
	MediaID        string
	Role           string
	Filename       string
	ExpectedSize   int64
	ChunkSize      int64
	TotalChunks    int64
	ExpectedSha256 string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) InsertUploadAsset(ctx context.Context, arg InsertUploadAssetParams) error {
	_, err := q.db.ExecContext(ctx, insertUploadAsset,
		arg.ID,
		arg.SessionID,
		arg.MediaID,
		arg.Role,
		arg.Filename,
		arg.ExpectedSize,
		arg.ChunkSize,
		arg.TotalChunks,
		arg.ExpectedSha256,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertUploadChunk = `-- name: InsertUploadChunk :execrows
INSERT INTO upload_chunks (asset_id, chunk_index, size_bytes, sha256, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (asset_id, chunk_index) DO NOTHING
`

type InsertUploadChunkParams struct {
	AssetID    string
	ChunkIndex int64
	SizeBytes  int64
	Sha256     string
	CreatedAt  time.Time
}

func (q *Queries) InsertUploadChunk(ctx context.Context, arg InsertUploadChunkParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertUploadChunk,
		arg.AssetID,
		arg.ChunkIndex,
		arg.SizeBytes,
		arg.Sha256,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertUploadSession = `-- name: InsertUploadSession :execrows
INSERT INTO upload_sessions (
    id, media_id, user_id, filename, retention_days, keep_original,
    expected_bytes, reserved_bytes, status, expires_at, created_at, updated_at
)
SELECT ?1, ?2, ?3, ?4,
       ?5, ?6, ?7,
       ?8, ?9, ?10,
       ?11, ?12
WHERE ?8 <= ?13 - (
    SELECT COALESCE(SUM(upload_sessions.reserved_bytes), 0)
    FROM upload_sessions
    WHERE user_id = ?3
      AND status IN ('active', 'failed', 'expired', 'canceled')
)
`

type InsertUploadSessionParams struct {
	ID               string
	MediaID          string
	UserID           int64
	Filename         string
	RetentionDays    int64
	KeepOriginal     int64
	ExpectedBytes    int64
	ReservedBytes    int64
	Status           string
	ExpiresAt        time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
	MaxReservedBytes int64
}

func (q *Queries) InsertUploadSession(ctx context.Context, arg InsertUploadSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertUploadSession,
		arg.ID,
		arg.MediaID,
		arg.UserID,
		arg.Filename,
		arg.RetentionDays,
		arg.KeepOriginal,
		arg.ExpectedBytes,
		arg.ReservedBytes,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.MaxReservedBytes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listExpiredUploadSessions = `-- name: ListExpiredUploadSessions :many
SELECT id, media_id, user_id, filename, retention_days, keep_original, expected_bytes, reserved_bytes, status, expires_at, created_at, updated_at FROM upload_sessions
WHERE expires_at <= ? AND status IN ('active', 'failed', 'expired', 'canceled')
`

func (q *Queries) ListExpiredUploadSessions(ctx context.Context, expiresAt time.Time) ([]UploadSession, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredUploadSessions, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadSession
	for rows.Next() {
		var i UploadSession
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.UserID,
			&i.Filename,
			&i.RetentionDays,
			&i.KeepOriginal,
			&i.ExpectedBytes,
			&i.ReservedBytes,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploadChunks = `-- name: ListUploadChunks :many
SELECT asset_id, chunk_index, size_bytes, sha256, created_at FROM upload_chunks WHERE asset_id = ? ORDER BY chunk_index ASC
`

func (q *Queries) ListUploadChunks(ctx context.Context, assetID string) ([]UploadChunk, error) {
	rows, err := q.db.QueryContext(ctx, listUploadChunks, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadChunk
	for rows.Next() {
		var i UploadChunk
		if err := rows.Scan(
			&i.AssetID,
			&i.ChunkIndex,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseUploadAssetFinalization = `-- name: ReleaseUploadAssetFinalization :exec
UPDATE upload_assets SET
    status = 'uploading',
    error_message = ?,
    updated_at = ?
WHERE id = ? AND status = 'finalizing'
`

type ReleaseUploadAssetFinalizationParams struct {
	ErrorMessage string
	UpdatedAt    time.Time
	ID           string
}

func (q *Queries) ReleaseUploadAssetFinalization(ctx context.Context, arg ReleaseUploadAssetFinalizationParams) error {
	_, err := q.db.ExecContext(ctx, releaseUploadAssetFinalization, arg.ErrorMessage, arg.UpdatedAt, arg.ID)
	return err
}

const updateUploadSessionStatus = `-- name: UpdateUploadSessionStatus :exec
UPDATE upload_sessions SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateUploadSessionStatusParams struct {
	Status    string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdateUploadSessionStatus(ctx context.Context, arg UpdateUploadSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUploadSessionStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
